Update some functions in examples
metagrover/ES6-for-humans pull request #43
Opened 2016-10-12 21:41 UTC by cesarcosta99

According to issue #42.

2016-10-13 08:37 UTC, metagrover requested changes
Should not return a resolve().

2016-10-13 08:37 UTC, metagrover commented on README.md
> +var hello = new Promise((resolve, reject) => resolve("Hello"));
Hi @cesarcosta99, you are returning resolve("Hello") here, you should instead write it as:

`new Promise((resolve, reject) => { resolve("Hello") });`

Similarly at line 641 and 643

2016-10-13 11:33 UTC, GoToLoop commented
`new Promise((resolve, reject) => { resolve("Hello") });`

Given it's only 1 statement, there's no need to wrap it w/ `{}`:    ;-D
`new Promise((resolve, reject) => resolve("Hello"));`

Unless of course you really want `undefined` returned instead.   O_o

2016-10-13 11:46 UTC, metagrover commented
I've seen both the formats used in various codebases, but what's the point of returning `resolve('Hello')`?

Here, we are executing a statement, not returning anything, so it makes sense to wrap it around `{ }`

2016-10-13 12:01 UTC, GoToLoop commented
The less boilerplate the better. If there's no problem returning **resolve()**, the lambda expression is cleaner w/o the extra `{}`!

2016-10-13 14:40 UTC, cesarcosta99 commented
@GoToLoop said what I was thinking; results in the same. But that's alright, I going to change to add the curly brackets.

2016-10-14 06:26 UTC, metagrover approved these changes

2016-10-14 06:27 UTC, merged

2016-10-14 06:38 UTC, metagrover commented
Sorry guys, I got busy yesterday. I also agree with @GoToLoop, absence of `{}` makes the code  a little prettier. But, now that the changes have been submitted, I accepted the PR.

Cheers.